Auto detect date/date-time formats
docknetwork/crypto-wasm-ts pull request #29
Opened 2023-09-18 20:27 UTC by cykoder

2023-09-18 20:34 UTC, cykoder commented on src/anonymous-credentials/schema.ts
> +      throw new Error(`${name} should be of numeric type as per schema but was ${JSON.stringify(valTyp, null, 2)}`);
@lovesh the reasoning behind this change is it wasnt so obvious to debug the error as itd say `but was [Object object]` in some cases

2023-09-19 06:15 UTC, lovesh requested changes

2023-09-19 06:15 UTC, lovesh commented on src/anonymous-credentials/schema.ts
> +  private static getTypeAndFormat(value: CredVal): any[] {
`any[]` -> `[string, string|undefined]`

2023-09-19 06:15 UTC, lovesh commented on src/anonymous-credentials/schema.ts
> +    let format: any = undefined;
`any` -> `string|undefined`

2023-09-19 16:55 UTC, lovesh approved these changes

2023-09-19 17:27 UTC, merged